export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFRESH: "POPULAR_REFRESH",//下拉刷新action
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL", // 加载失败action
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS", // 加载成功action
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",// 上拉加载成功
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL", // 上拉加载失败
    FLUSH_POPULAR_FAVORITE: "FLUSH_POPULAR_FAVORITE", // 收藏刷新状态
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS:"TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",// 收藏刷新状态
    FLUSH_TRENDING_FAVORITE: "FLUSH_TRENDING_FAVORITE", // 收藏刷新状态
    FAVORITE_LOAD_SUCCESS: "FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_DATA: "FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_FAIL: "FAVORITE_LOAD_FAIL",
    LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS", // 语言加载成功
}