export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFRESH: "POPULAR_REFRESH",//下拉刷新action
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL", // 加载失败action
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS", // 加载成功action
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",// 上拉加载成功
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL", // 上拉加载失败

}