export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFRESH: "POPULAR_REFRESH",//下拉刷新action
    LOAD_POPULAR_FAIL: "LOAD_POPULAR_FAIL", // 加载失败action
    LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS", // 加载失败action
}